#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef FINVUSDK_SWIFT_H
#define FINVUSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Dispatch;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FinvuSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS_NAMED("AccountAggregator")
@interface FinvuAccountAggregator : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuFIEncryptedDataView;

SWIFT_CLASS_NAMED("AccountDataFetchResponse")
@interface FinvuAccountDataFetchResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull fipId;
@property (nonatomic, readonly, copy) NSArray<FinvuFIEncryptedDataView *> * _Nonnull decryptedInfo;
- (nonnull instancetype)initWithFipId:(NSString * _Nonnull)fipId decryptedInfo:(NSArray<FinvuFIEncryptedDataView *> * _Nonnull)decryptedInfo OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDate;

SWIFT_CLASS_NAMED("AccountDataRequestResponse")
@interface FinvuAccountDataRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable transactionId;
@property (nonatomic, readonly, copy) NSDate * _Nullable timestamp;
@property (nonatomic, readonly, copy) NSString * _Nullable consentId;
@property (nonatomic, readonly, copy) NSString * _Nullable sessionId;
- (nonnull instancetype)initWithTransactionId:(NSString * _Nonnull)transactionId timestamp:(NSDate * _Nullable)timestamp consentId:(NSString * _Nonnull)consentId sessionId:(NSString * _Nonnull)sessionId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("AccountLinkingRequestReference")
@interface FinvuAccountLinkingRequestReference : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull referenceNumber;
- (nonnull instancetype)initWithReferenceNumber:(NSString * _Nonnull)referenceNumber OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuLinkedAccountInfo;

SWIFT_CLASS_NAMED("ConfirmAccountLinkingInfo")
@interface FinvuConfirmAccountLinkingInfo : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuLinkedAccountInfo *> * _Nonnull linkedAccounts;
- (nonnull instancetype)initWithLinkedAccounts:(NSArray<FinvuLinkedAccountInfo *> * _Nonnull)linkedAccounts OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentAccountDetails")
@interface FinvuConsentAccountDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull fiType;
@property (nonatomic, readonly, copy) NSString * _Nonnull fipId;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountType;
@property (nonatomic, readonly, copy) NSString * _Nullable accountReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull maskedAccountNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull linkReferenceNumber;
- (nonnull instancetype)initWithFiType:(NSString * _Nonnull)fiType fipId:(NSString * _Nonnull)fipId accountType:(NSString * _Nonnull)accountType accountReferenceNumber:(NSString * _Nullable)accountReferenceNumber maskedAccountNumber:(NSString * _Nonnull)maskedAccountNumber linkReferenceNumber:(NSString * _Nonnull)linkReferenceNumber OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentDataFrequency")
@interface FinvuConsentDataFrequency : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull unit;
@property (nonatomic, readonly) double value;
- (nonnull instancetype)initWithUnit:(NSString * _Nonnull)unit value:(double)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentDataLifePeriod")
@interface FinvuConsentDataLifePeriod : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull unit;
@property (nonatomic, readonly) double value;
- (nonnull instancetype)initWithUnit:(NSString * _Nonnull)unit value:(double)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentHandleStatusResponse")
@interface FinvuConsentHandleStatusResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (nonnull instancetype)initWithStatus:(NSString * _Nonnull)status OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentHistory")
@interface FinvuConsentHistory : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull consentId;
@property (nonatomic, readonly, copy) NSDate * _Nullable consentTimestamp;
- (nonnull instancetype)initWithConsentId:(NSString * _Nonnull)consentId consentTimestamp:(NSDate * _Nullable)consentTimestamp OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentHistoryResponse")
@interface FinvuConsentHistoryResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuConsentHistory *> * _Nonnull consentHistory;
- (nonnull instancetype)initWithConsentHistory:(NSArray<FinvuConsentHistory *> * _Nonnull)consentHistory OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentPurposeInfo")
@interface FinvuConsentPurposeInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
@property (nonatomic, readonly, copy) NSString * _Nonnull text;
- (nonnull instancetype)initWithCode:(NSString * _Nonnull)code text:(NSString * _Nonnull)text OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentReport")
@interface FinvuConsentReport : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull report;
- (nonnull instancetype)initWithReport:(NSString * _Nonnull)report OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuFinancialInformationUserInfo;
@class FinvuDateTimeRange;

SWIFT_CLASS_NAMED("ConsentRequestDetailInfo")
@interface FinvuConsentRequestDetailInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable consentId;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentHandle;
@property (nonatomic, readonly, strong) FinvuFinancialInformationUserInfo * _Nonnull financialInformationUser;
@property (nonatomic, readonly, strong) FinvuConsentPurposeInfo * _Nonnull consentPurposeInfo;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull consentDisplayDescriptions;
@property (nonatomic, readonly, strong) FinvuDateTimeRange * _Nonnull consentDateTimeRange;
@property (nonatomic, readonly, strong) FinvuDateTimeRange * _Nonnull dataDateTimeRange;
@property (nonatomic, readonly, strong) FinvuConsentDataLifePeriod * _Nonnull consentDataLifePeriod;
@property (nonatomic, readonly, strong) FinvuConsentDataFrequency * _Nonnull consentDataFrequency;
@property (nonatomic, readonly, copy) NSDate * _Nullable statusLastUpdateTimestamp;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable fiTypes;
- (nonnull instancetype)initWithConsentId:(NSString * _Nullable)consentId consentHandle:(NSString * _Nonnull)consentHandle statusLastUpdateTimestamp:(NSDate * _Nullable)statusLastUpdateTimestamp financialInformationUser:(FinvuFinancialInformationUserInfo * _Nonnull)financialInformationUser consentPurposeInfo:(FinvuConsentPurposeInfo * _Nonnull)consentPurposeInfo consentDisplayDescriptions:(NSArray<NSString *> * _Nonnull)consentDisplayDescriptions consentDateTimeRange:(FinvuDateTimeRange * _Nonnull)consentDateTimeRange dataDateTimeRange:(FinvuDateTimeRange * _Nonnull)dataDateTimeRange consentDataLifePeriod:(FinvuConsentDataLifePeriod * _Nonnull)consentDataLifePeriod consentDataFrequency:(FinvuConsentDataFrequency * _Nonnull)consentDataFrequency fiTypes:(NSArray<NSString *> * _Nullable)fiTypes OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentRequestDetailResponse")
@interface FinvuConsentRequestDetailResponse : NSObject
@property (nonatomic, readonly, strong) FinvuConsentRequestDetailInfo * _Nonnull detail;
- (nonnull instancetype)initWithDetail:(FinvuConsentRequestDetailInfo * _Nonnull)detail OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("DateTimeRange")
@interface FinvuDateTimeRange : NSObject
@property (nonatomic, readonly, copy) NSDate * _Nonnull from;
@property (nonatomic, readonly, copy) NSDate * _Nonnull to;
- (nonnull instancetype)initFrom:(NSDate * _Nonnull)from to:(NSDate * _Nonnull)to OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("DiscoveredAccountInfo")
@interface FinvuDiscoveredAccountInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull accountType;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull maskedAccountNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull fiType;
- (nonnull instancetype)initWithAccountType:(NSString * _Nonnull)accountType accountReferenceNumber:(NSString * _Nonnull)accountReferenceNumber maskedAccountNumber:(NSString * _Nonnull)maskedAccountNumber fiType:(NSString * _Nonnull)fiType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("DiscoveredAccountsResponse")
@interface FinvuDiscoveredAccountsResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuDiscoveredAccountInfo *> * _Nonnull accounts;
- (nonnull instancetype)initWithAccounts:(NSArray<FinvuDiscoveredAccountInfo *> * _Nonnull)accounts OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("EntityInfo")
@interface FinvuEntityInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull entityId;
@property (nonatomic, readonly, copy) NSString * _Nonnull entityName;
@property (nonatomic, readonly, copy) NSString * _Nullable entityIconUri;
@property (nonatomic, readonly, copy) NSString * _Nullable entityLogoUri;
@property (nonatomic, readonly, copy) NSString * _Nullable entityLogoWithNameUri;
- (nonnull instancetype)initWithEntityId:(NSString * _Nonnull)entityId entityName:(NSString * _Nonnull)entityName entityIconUri:(NSString * _Nullable)entityIconUri entityLogoUri:(NSString * _Nullable)entityLogoUri entityLogoWithNameUri:(NSString * _Nullable)entityLogoWithNameUri OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FIDecryptedDataInfo")
@interface FinvuFIEncryptedDataView : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull linkReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable accountReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull maskedAccountNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable fiType;
@property (nonatomic, readonly, copy) NSString * _Nullable accountType;
@property (nonatomic, readonly, copy) NSString * _Nonnull decryptedData;
- (nonnull instancetype)initWithLinkReferenceNumber:(NSString * _Nonnull)linkReferenceNumber accountReferenceNumber:(NSString * _Nullable)accountReferenceNumber maskedAccountNumber:(NSString * _Nonnull)maskedAccountNumber fiType:(NSString * _Nullable)fiType accountType:(NSString * _Nullable)accountType decryptedData:(NSString * _Nonnull)decryptedData OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuFIPFiTypeIdentifier;

SWIFT_CLASS_NAMED("FIPDetails")
@interface FinvuFIPDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull fipId;
@property (nonatomic, readonly, copy) NSArray<FinvuFIPFiTypeIdentifier *> * _Nonnull typeIdentifiers;
- (nonnull instancetype)initWithFipId:(NSString * _Nonnull)fipId typeIdenifiers:(NSArray<FinvuFIPFiTypeIdentifier *> * _Nonnull)typeIdenifiers OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuTypeIdentifier;

SWIFT_CLASS_NAMED("FIPFiTypeIdentifier")
@interface FinvuFIPFiTypeIdentifier : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull fiType;
@property (nonatomic, readonly, copy) NSArray<FinvuTypeIdentifier *> * _Nonnull identifiers;
- (nonnull instancetype)initWithFiType:(NSString * _Nonnull)fiType identifiers:(NSArray<FinvuTypeIdentifier *> * _Nonnull)identifiers OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FIPInfo")
@interface FinvuFIPInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull fipId;
@property (nonatomic, readonly, copy) NSString * _Nullable productName;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull fipFitypes;
@property (nonatomic, readonly, copy) NSString * _Nullable fipFsr;
@property (nonatomic, readonly, copy) NSString * _Nullable productDesc;
@property (nonatomic, readonly, copy) NSString * _Nullable productIconUri;
@property (nonatomic, readonly) BOOL enabled;
- (nonnull instancetype)initWithFipId:(NSString * _Nonnull)fipId productName:(NSString * _Nullable)productName fipFitypes:(NSArray<NSString *> * _Nonnull)fipFitypes fipFsr:(NSString * _Nullable)fipFsr productDesc:(NSString * _Nullable)productDesc productIconUri:(NSString * _Nullable)productIconUri enabled:(BOOL)enabled OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FIPReference")
@interface FinvuFIPReference : NSObject
- (nonnull instancetype)initWithFipId:(NSString * _Nonnull)fipId fipName:(NSString * _Nonnull)fipName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FIPSearchResponse")
@interface FinvuFIPSearchResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuFIPInfo *> * _Nonnull searchOptions;
- (nonnull instancetype)initWithSearchOptions:(NSArray<FinvuFIPInfo *> * _Nonnull)searchOptions OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuOfflineMessageInfo;

SWIFT_CLASS_NAMED("FetchOfflineMessageResponse")
@interface FinvuFetchOfflineMessageResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuOfflineMessageInfo *> * _Nullable messages;
- (nonnull instancetype)initWithMessages:(NSArray<FinvuOfflineMessageInfo *> * _Nullable)messages OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FinancialInformationEntityInfo")
@interface FinvuFinancialInformationUserInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;

SWIFT_PROTOCOL("_TtP8FinvuSDK11FinvuConfig_")
@protocol FinvuConfig
@property (nonatomic, readonly, copy) NSURL * _Nonnull finvuEndpoint;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable certificatePins;
@end


SWIFT_CLASS_NAMED("FinvuConsentInfo")
@interface FinvuConsentInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable fipId;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentId;
- (nonnull instancetype)initWithFipId:(NSString * _Nullable)fipId consentId:(NSString * _Nonnull)consentId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FinvuDeviceBinding")
@interface FinvuDeviceBinding : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull secret;
- (nonnull instancetype)initWithSecret:(NSString * _Nonnull)secret OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FinvuLoginResponse")
@interface FinvuLoginResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSError;
@class FinvuLoginOtpReference;
@class FinvuHandleInfo;
@class FinvuLinkedAccountsReponse;
@class FinvuTypeIdentifierInfo;
@class FinvuLinkedAccountDetailsInfo;
@class FinvuProcessAccountConsentResponse;
@class FinvuUserConsentInfoDetails;

SWIFT_CLASS("_TtC8FinvuSDK12FinvuManager")
@interface FinvuManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) FinvuManager * _Nonnull shared;)
+ (FinvuManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(FinvuManager * _Nonnull)value;
- (void)setCompletionDispatchQueueWithQueue:(dispatch_queue_t _Nonnull)queue;
- (void)initializeWithConfig:(id <FinvuConfig> _Nonnull)config;
- (void)connectWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)disconnect;
- (BOOL)isConnected SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasSession SWIFT_WARN_UNUSED_RESULT;
- (void)loginWithUsername:(NSString * _Nullable)username mobileNumber:(NSString * _Nullable)mobileNumber consentHandleId:(NSString * _Nonnull)consentHandleId completion:(void (^ _Nonnull)(FinvuLoginOtpReference * _Nullable, NSError * _Nullable))completion;
- (void)verifyLoginOtpWithOtp:(NSString * _Nonnull)otp otpReference:(NSString * _Nonnull)otpReference completion:(void (^ _Nonnull)(FinvuHandleInfo * _Nullable, NSError * _Nullable))completion;
- (void)initiateMobileVerificationWithMobileNumber:(NSString * _Nonnull)mobileNumber completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)completeMobileVerificationWithMobileNumber:(NSString * _Nonnull)mobileNumber otp:(NSString * _Nonnull)otp completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchLinkedAccountsWithCompletion:(void (^ _Nonnull)(FinvuLinkedAccountsReponse * _Nullable, NSError * _Nullable))completion;
- (void)discoverAccountsWithFipDetails:(FinvuFIPDetails * _Nonnull)fipDetails fiTypes:(NSArray<NSString *> * _Nonnull)fiTypes identifiers:(NSArray<FinvuTypeIdentifierInfo *> * _Nonnull)identifiers completion:(void (^ _Nonnull)(FinvuDiscoveredAccountsResponse * _Nullable, NSError * _Nullable))completion;
- (void)linkAccountsWithFipDetails:(FinvuFIPDetails * _Nonnull)fipDetails accounts:(NSArray<FinvuDiscoveredAccountInfo *> * _Nonnull)accounts completion:(void (^ _Nonnull)(FinvuAccountLinkingRequestReference * _Nullable, NSError * _Nullable))completion;
- (void)confirmAccountLinkingWithLinkingReference:(FinvuAccountLinkingRequestReference * _Nonnull)linkingReference otp:(NSString * _Nonnull)otp completion:(void (^ _Nonnull)(FinvuConfirmAccountLinkingInfo * _Nullable, NSError * _Nullable))completion;
- (void)getConsentRequestDetailsWithConsentHandleId:(NSString * _Nonnull)consentHandleId completion:(void (^ _Nonnull)(FinvuConsentRequestDetailResponse * _Nullable, NSError * _Nullable))completion;
- (void)approveAccountConsentRequestWithConsentDetail:(FinvuConsentRequestDetailInfo * _Nonnull)consentDetail linkedAccounts:(NSArray<FinvuLinkedAccountDetailsInfo *> * _Nonnull)linkedAccounts completion:(void (^ _Nonnull)(FinvuProcessAccountConsentResponse * _Nullable, NSError * _Nullable))completion;
- (void)denyAccountConsentRequestWithConsentDetail:(FinvuConsentRequestDetailInfo * _Nonnull)consentDetail completion:(void (^ _Nonnull)(FinvuProcessAccountConsentResponse * _Nullable, NSError * _Nullable))completion;
- (void)revokeConsentWithConsent:(FinvuUserConsentInfoDetails * _Nonnull)consent accountAggregator:(FinvuAccountAggregator * _Nullable)accountAggregator fipDetails:(FinvuFIPReference * _Nullable)fipDetails completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)getConsentHandleStatusWithHandleId:(NSString * _Nonnull)handleId completion:(void (^ _Nonnull)(FinvuConsentHandleStatusResponse * _Nullable, NSError * _Nullable))completion;
- (void)fipsAllFIPOptionsWithCompletion:(void (^ _Nonnull)(FinvuFIPSearchResponse * _Nullable, NSError * _Nullable))completion;
- (void)fetchFIPDetailsWithFipId:(NSString * _Nonnull)fipId completion:(void (^ _Nonnull)(FinvuFIPDetails * _Nullable, NSError * _Nullable))completion;
- (void)getEntityInfoWithEntityId:(NSString * _Nonnull)entityId entityType:(NSString * _Nonnull)entityType completion:(void (^ _Nonnull)(FinvuEntityInfo * _Nullable, NSError * _Nullable))completion;
- (void)logoutWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end


SWIFT_CLASS_NAMED("ForgotHandle")
@interface FinvuForgotHandle : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull userIds;
- (nonnull instancetype)initWithUserIds:(NSArray<NSString *> * _Nonnull)userIds OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("HandleInfo")
@interface FinvuHandleInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LinkedAccountDetailsInfo")
@interface FinvuLinkedAccountDetailsInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
@property (nonatomic, readonly, copy) NSString * _Nonnull fipId;
@property (nonatomic, readonly, copy) NSString * _Nonnull fipName;
@property (nonatomic, readonly, copy) NSString * _Nonnull maskedAccountNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull linkReferenceNumber;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable consentIdList;
@property (nonatomic, readonly, copy) NSString * _Nonnull fiType;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountType;
@property (nonatomic, readonly, copy) NSDate * _Nullable linkedAccountUpdateTimestamp;
@property (nonatomic, readonly, copy) NSString * _Nonnull authenticatorType;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId fipId:(NSString * _Nonnull)fipId fipName:(NSString * _Nonnull)fipName maskedAccountNumber:(NSString * _Nonnull)maskedAccountNumber accountReferenceNumber:(NSString * _Nonnull)accountReferenceNumber linkReferenceNumber:(NSString * _Nonnull)linkReferenceNumber consentIdList:(NSArray<NSString *> * _Nullable)consentIdList fiType:(NSString * _Nonnull)fiType accountType:(NSString * _Nonnull)accountType linkedAccountUpdateTimestamp:(NSDate * _Nullable)linkedAccountUpdateTimestamp authenticatorType:(NSString * _Nonnull)authenticatorType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LinkedAccountInfo")
@interface FinvuLinkedAccountInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull customerAddress;
@property (nonatomic, readonly, copy) NSString * _Nonnull linkReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (nonnull instancetype)initWithCustomerAddress:(NSString * _Nonnull)customerAddress linkReferenceNumber:(NSString * _Nonnull)linkReferenceNumber accountReferenceNumber:(NSString * _Nonnull)accountReferenceNumber status:(NSString * _Nonnull)status OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LinkedAccountsResponse")
@interface FinvuLinkedAccountsReponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuLinkedAccountDetailsInfo *> * _Nullable linkedAccounts;
- (nonnull instancetype)initWithLinkedAccounts:(NSArray<FinvuLinkedAccountDetailsInfo *> * _Nullable)linkedAccounts OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LoginOtpReference")
@interface FinvuLoginOtpReference : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull reference;
- (nonnull instancetype)initWithReference:(NSString * _Nonnull)reference OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS_NAMED("OfflineMessageInfo")
@interface FinvuOfflineMessageInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageId;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageAcked;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageOriginator;
@property (nonatomic, readonly, copy) NSString * _Nullable messageOriginatorName;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageText;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageTimestamp;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageType;
@property (nonatomic, readonly, copy) NSString * _Nonnull requestConsentId;
@property (nonatomic, readonly, copy) NSString * _Nullable requestSessionId;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId messageId:(NSString * _Nonnull)messageId messageAcked:(NSString * _Nonnull)messageAcked messageOriginator:(NSString * _Nonnull)messageOriginator messageOriginatorName:(NSString * _Nullable)messageOriginatorName messageText:(NSString * _Nonnull)messageText messageTimestamp:(NSString * _Nonnull)messageTimestamp messageType:(NSString * _Nonnull)messageType requestConsentId:(NSString * _Nonnull)requestConsentId requestSessionId:(NSString * _Nullable)requestSessionId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PendingConsentRequestsResponse")
@interface FinvuPendingConsentRequestsResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuConsentRequestDetailInfo *> * _Nonnull details;
- (nonnull instancetype)initWithDetails:(NSArray<FinvuConsentRequestDetailInfo *> * _Nonnull)details OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ProcessAccountConsentResponse")
@interface FinvuProcessAccountConsentResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable consentIntentId;
@property (nonatomic, readonly, copy) NSArray<FinvuConsentInfo *> * _Nullable consentsInfo;
- (nonnull instancetype)initWithConsentIntentId:(NSString * _Nullable)consentIntentId consentsInfo:(NSArray<FinvuConsentInfo *> * _Nullable)consentsInfo OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("TypeIdentifier")
@interface FinvuTypeIdentifier : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category type:(NSString * _Nonnull)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("TypeIdentifierInfo")
@interface FinvuTypeIdentifierInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull value;
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category type:(NSString * _Nonnull)type value:(NSString * _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UserConsentDetails")
@interface FinvuUserConsentDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable consentHandle;
@property (nonatomic, readonly, copy) NSString * _Nullable consentId;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentStatus;
@property (nonatomic, readonly, copy) NSDate * _Nullable statusLastUpdateTimestamp;
@property (nonatomic, readonly, strong) FinvuFinancialInformationUserInfo * _Nullable financialInformationProvider;
@property (nonatomic, readonly, strong) FinvuFinancialInformationUserInfo * _Nullable financialInformationUser;
@property (nonatomic, readonly, strong) FinvuConsentPurposeInfo * _Nonnull consentPurposeInfo;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull consentDisplayDescriptions;
@property (nonatomic, readonly, strong) FinvuDateTimeRange * _Nonnull consentDateTimeRange;
@property (nonatomic, readonly, strong) FinvuDateTimeRange * _Nonnull dataDateTimeRange;
@property (nonatomic, readonly, strong) FinvuConsentDataLifePeriod * _Nonnull consentDataLifePeriod;
@property (nonatomic, readonly, strong) FinvuConsentDataFrequency * _Nonnull consentDataFrequency;
@property (nonatomic, readonly, copy) NSArray<FinvuConsentAccountDetails *> * _Nonnull accounts;
@property (nonatomic, readonly, strong) FinvuAccountAggregator * _Nonnull accountAggregator;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UserConsentInfo")
@interface FinvuUserConsentInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull consentIntentId;
@property (nonatomic, readonly, copy) NSString * _Nullable consentIntentEntityId;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentIntentEntityName;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull consentIdList;
@property (nonatomic, readonly, copy) NSDate * _Nonnull consentIntentUpdateTimestamp;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentPurposeText;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
- (nonnull instancetype)initWithConsentIntentId:(NSString * _Nonnull)consentIntentId consentIntentEntityId:(NSString * _Nullable)consentIntentEntityId consentIntentEntityName:(NSString * _Nonnull)consentIntentEntityName consentIdList:(NSArray<NSString *> * _Nonnull)consentIdList consentIntentUpdateTimestamp:(NSDate * _Nonnull)consentIntentUpdateTimestamp consentPurposeText:(NSString * _Nonnull)consentPurposeText status:(NSString * _Nullable)status OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UserConsentInfoDetails")
@interface FinvuUserConsentInfoDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull consentId;
@property (nonatomic, readonly, copy) NSString * _Nullable consentIntentEntityId;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentIntentEntityName;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull consentIdList;
@property (nonatomic, readonly, copy) NSDate * _Nonnull consentIntentUpdateTimestamp;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentPurposeText;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
- (nonnull instancetype)initWithConsentId:(NSString * _Nonnull)consentId consentIntentEntityId:(NSString * _Nullable)consentIntentEntityId consentIntentEntityName:(NSString * _Nonnull)consentIntentEntityName consentIdList:(NSArray<NSString *> * _Nonnull)consentIdList consentIntentUpdateTimestamp:(NSDate * _Nonnull)consentIntentUpdateTimestamp consentPurposeText:(NSString * _Nonnull)consentPurposeText status:(NSString * _Nullable)status OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UserConsentResponse")
@interface FinvuUserConsentResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuUserConsentInfo *> * _Nonnull userConsents;
- (nonnull instancetype)initWithUserConsents:(NSArray<FinvuUserConsentInfo *> * _Nonnull)userConsents OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UserInfo")
@interface FinvuUserInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
@property (nonatomic, readonly, copy) NSString * _Nonnull mobileNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull emailId;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId mobileNumber:(NSString * _Nonnull)mobileNumber emailId:(NSString * _Nonnull)emailId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef FINVUSDK_SWIFT_H
#define FINVUSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Dispatch;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FinvuSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS_NAMED("AccountAggregator")
@interface FinvuAccountAggregator : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuFIEncryptedDataView;

SWIFT_CLASS_NAMED("AccountDataFetchResponse")
@interface FinvuAccountDataFetchResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull fipId;
@property (nonatomic, readonly, copy) NSArray<FinvuFIEncryptedDataView *> * _Nonnull decryptedInfo;
- (nonnull instancetype)initWithFipId:(NSString * _Nonnull)fipId decryptedInfo:(NSArray<FinvuFIEncryptedDataView *> * _Nonnull)decryptedInfo OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDate;

SWIFT_CLASS_NAMED("AccountDataRequestResponse")
@interface FinvuAccountDataRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable transactionId;
@property (nonatomic, readonly, copy) NSDate * _Nullable timestamp;
@property (nonatomic, readonly, copy) NSString * _Nullable consentId;
@property (nonatomic, readonly, copy) NSString * _Nullable sessionId;
- (nonnull instancetype)initWithTransactionId:(NSString * _Nonnull)transactionId timestamp:(NSDate * _Nullable)timestamp consentId:(NSString * _Nonnull)consentId sessionId:(NSString * _Nonnull)sessionId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("AccountLinkingRequestReference")
@interface FinvuAccountLinkingRequestReference : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull referenceNumber;
- (nonnull instancetype)initWithReferenceNumber:(NSString * _Nonnull)referenceNumber OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuLinkedAccountInfo;

SWIFT_CLASS_NAMED("ConfirmAccountLinkingInfo")
@interface FinvuConfirmAccountLinkingInfo : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuLinkedAccountInfo *> * _Nonnull linkedAccounts;
- (nonnull instancetype)initWithLinkedAccounts:(NSArray<FinvuLinkedAccountInfo *> * _Nonnull)linkedAccounts OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentAccountDetails")
@interface FinvuConsentAccountDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull fiType;
@property (nonatomic, readonly, copy) NSString * _Nonnull fipId;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountType;
@property (nonatomic, readonly, copy) NSString * _Nullable accountReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull maskedAccountNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull linkReferenceNumber;
- (nonnull instancetype)initWithFiType:(NSString * _Nonnull)fiType fipId:(NSString * _Nonnull)fipId accountType:(NSString * _Nonnull)accountType accountReferenceNumber:(NSString * _Nullable)accountReferenceNumber maskedAccountNumber:(NSString * _Nonnull)maskedAccountNumber linkReferenceNumber:(NSString * _Nonnull)linkReferenceNumber OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentDataFrequency")
@interface FinvuConsentDataFrequency : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull unit;
@property (nonatomic, readonly) double value;
- (nonnull instancetype)initWithUnit:(NSString * _Nonnull)unit value:(double)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentDataLifePeriod")
@interface FinvuConsentDataLifePeriod : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull unit;
@property (nonatomic, readonly) double value;
- (nonnull instancetype)initWithUnit:(NSString * _Nonnull)unit value:(double)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentHandleStatusResponse")
@interface FinvuConsentHandleStatusResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (nonnull instancetype)initWithStatus:(NSString * _Nonnull)status OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentHistory")
@interface FinvuConsentHistory : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull consentId;
@property (nonatomic, readonly, copy) NSDate * _Nullable consentTimestamp;
- (nonnull instancetype)initWithConsentId:(NSString * _Nonnull)consentId consentTimestamp:(NSDate * _Nullable)consentTimestamp OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentHistoryResponse")
@interface FinvuConsentHistoryResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuConsentHistory *> * _Nonnull consentHistory;
- (nonnull instancetype)initWithConsentHistory:(NSArray<FinvuConsentHistory *> * _Nonnull)consentHistory OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentPurposeInfo")
@interface FinvuConsentPurposeInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
@property (nonatomic, readonly, copy) NSString * _Nonnull text;
- (nonnull instancetype)initWithCode:(NSString * _Nonnull)code text:(NSString * _Nonnull)text OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentReport")
@interface FinvuConsentReport : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull report;
- (nonnull instancetype)initWithReport:(NSString * _Nonnull)report OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuFinancialInformationUserInfo;
@class FinvuDateTimeRange;

SWIFT_CLASS_NAMED("ConsentRequestDetailInfo")
@interface FinvuConsentRequestDetailInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable consentId;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentHandle;
@property (nonatomic, readonly, strong) FinvuFinancialInformationUserInfo * _Nonnull financialInformationUser;
@property (nonatomic, readonly, strong) FinvuConsentPurposeInfo * _Nonnull consentPurposeInfo;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull consentDisplayDescriptions;
@property (nonatomic, readonly, strong) FinvuDateTimeRange * _Nonnull consentDateTimeRange;
@property (nonatomic, readonly, strong) FinvuDateTimeRange * _Nonnull dataDateTimeRange;
@property (nonatomic, readonly, strong) FinvuConsentDataLifePeriod * _Nonnull consentDataLifePeriod;
@property (nonatomic, readonly, strong) FinvuConsentDataFrequency * _Nonnull consentDataFrequency;
@property (nonatomic, readonly, copy) NSDate * _Nullable statusLastUpdateTimestamp;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable fiTypes;
- (nonnull instancetype)initWithConsentId:(NSString * _Nullable)consentId consentHandle:(NSString * _Nonnull)consentHandle statusLastUpdateTimestamp:(NSDate * _Nullable)statusLastUpdateTimestamp financialInformationUser:(FinvuFinancialInformationUserInfo * _Nonnull)financialInformationUser consentPurposeInfo:(FinvuConsentPurposeInfo * _Nonnull)consentPurposeInfo consentDisplayDescriptions:(NSArray<NSString *> * _Nonnull)consentDisplayDescriptions consentDateTimeRange:(FinvuDateTimeRange * _Nonnull)consentDateTimeRange dataDateTimeRange:(FinvuDateTimeRange * _Nonnull)dataDateTimeRange consentDataLifePeriod:(FinvuConsentDataLifePeriod * _Nonnull)consentDataLifePeriod consentDataFrequency:(FinvuConsentDataFrequency * _Nonnull)consentDataFrequency fiTypes:(NSArray<NSString *> * _Nullable)fiTypes OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ConsentRequestDetailResponse")
@interface FinvuConsentRequestDetailResponse : NSObject
@property (nonatomic, readonly, strong) FinvuConsentRequestDetailInfo * _Nonnull detail;
- (nonnull instancetype)initWithDetail:(FinvuConsentRequestDetailInfo * _Nonnull)detail OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("DateTimeRange")
@interface FinvuDateTimeRange : NSObject
@property (nonatomic, readonly, copy) NSDate * _Nonnull from;
@property (nonatomic, readonly, copy) NSDate * _Nonnull to;
- (nonnull instancetype)initFrom:(NSDate * _Nonnull)from to:(NSDate * _Nonnull)to OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("DiscoveredAccountInfo")
@interface FinvuDiscoveredAccountInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull accountType;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull maskedAccountNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull fiType;
- (nonnull instancetype)initWithAccountType:(NSString * _Nonnull)accountType accountReferenceNumber:(NSString * _Nonnull)accountReferenceNumber maskedAccountNumber:(NSString * _Nonnull)maskedAccountNumber fiType:(NSString * _Nonnull)fiType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("DiscoveredAccountsResponse")
@interface FinvuDiscoveredAccountsResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuDiscoveredAccountInfo *> * _Nonnull accounts;
- (nonnull instancetype)initWithAccounts:(NSArray<FinvuDiscoveredAccountInfo *> * _Nonnull)accounts OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("EntityInfo")
@interface FinvuEntityInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull entityId;
@property (nonatomic, readonly, copy) NSString * _Nonnull entityName;
@property (nonatomic, readonly, copy) NSString * _Nullable entityIconUri;
@property (nonatomic, readonly, copy) NSString * _Nullable entityLogoUri;
@property (nonatomic, readonly, copy) NSString * _Nullable entityLogoWithNameUri;
- (nonnull instancetype)initWithEntityId:(NSString * _Nonnull)entityId entityName:(NSString * _Nonnull)entityName entityIconUri:(NSString * _Nullable)entityIconUri entityLogoUri:(NSString * _Nullable)entityLogoUri entityLogoWithNameUri:(NSString * _Nullable)entityLogoWithNameUri OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FIDecryptedDataInfo")
@interface FinvuFIEncryptedDataView : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull linkReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable accountReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull maskedAccountNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable fiType;
@property (nonatomic, readonly, copy) NSString * _Nullable accountType;
@property (nonatomic, readonly, copy) NSString * _Nonnull decryptedData;
- (nonnull instancetype)initWithLinkReferenceNumber:(NSString * _Nonnull)linkReferenceNumber accountReferenceNumber:(NSString * _Nullable)accountReferenceNumber maskedAccountNumber:(NSString * _Nonnull)maskedAccountNumber fiType:(NSString * _Nullable)fiType accountType:(NSString * _Nullable)accountType decryptedData:(NSString * _Nonnull)decryptedData OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuFIPFiTypeIdentifier;

SWIFT_CLASS_NAMED("FIPDetails")
@interface FinvuFIPDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull fipId;
@property (nonatomic, readonly, copy) NSArray<FinvuFIPFiTypeIdentifier *> * _Nonnull typeIdentifiers;
- (nonnull instancetype)initWithFipId:(NSString * _Nonnull)fipId typeIdenifiers:(NSArray<FinvuFIPFiTypeIdentifier *> * _Nonnull)typeIdenifiers OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuTypeIdentifier;

SWIFT_CLASS_NAMED("FIPFiTypeIdentifier")
@interface FinvuFIPFiTypeIdentifier : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull fiType;
@property (nonatomic, readonly, copy) NSArray<FinvuTypeIdentifier *> * _Nonnull identifiers;
- (nonnull instancetype)initWithFiType:(NSString * _Nonnull)fiType identifiers:(NSArray<FinvuTypeIdentifier *> * _Nonnull)identifiers OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FIPInfo")
@interface FinvuFIPInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull fipId;
@property (nonatomic, readonly, copy) NSString * _Nullable productName;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull fipFitypes;
@property (nonatomic, readonly, copy) NSString * _Nullable fipFsr;
@property (nonatomic, readonly, copy) NSString * _Nullable productDesc;
@property (nonatomic, readonly, copy) NSString * _Nullable productIconUri;
@property (nonatomic, readonly) BOOL enabled;
- (nonnull instancetype)initWithFipId:(NSString * _Nonnull)fipId productName:(NSString * _Nullable)productName fipFitypes:(NSArray<NSString *> * _Nonnull)fipFitypes fipFsr:(NSString * _Nullable)fipFsr productDesc:(NSString * _Nullable)productDesc productIconUri:(NSString * _Nullable)productIconUri enabled:(BOOL)enabled OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FIPReference")
@interface FinvuFIPReference : NSObject
- (nonnull instancetype)initWithFipId:(NSString * _Nonnull)fipId fipName:(NSString * _Nonnull)fipName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FIPSearchResponse")
@interface FinvuFIPSearchResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuFIPInfo *> * _Nonnull searchOptions;
- (nonnull instancetype)initWithSearchOptions:(NSArray<FinvuFIPInfo *> * _Nonnull)searchOptions OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FinvuOfflineMessageInfo;

SWIFT_CLASS_NAMED("FetchOfflineMessageResponse")
@interface FinvuFetchOfflineMessageResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuOfflineMessageInfo *> * _Nullable messages;
- (nonnull instancetype)initWithMessages:(NSArray<FinvuOfflineMessageInfo *> * _Nullable)messages OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FinancialInformationEntityInfo")
@interface FinvuFinancialInformationUserInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;

SWIFT_PROTOCOL("_TtP8FinvuSDK11FinvuConfig_")
@protocol FinvuConfig
@property (nonatomic, readonly, copy) NSURL * _Nonnull finvuEndpoint;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable certificatePins;
@end


SWIFT_CLASS_NAMED("FinvuConsentInfo")
@interface FinvuConsentInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable fipId;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentId;
- (nonnull instancetype)initWithFipId:(NSString * _Nullable)fipId consentId:(NSString * _Nonnull)consentId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FinvuDeviceBinding")
@interface FinvuDeviceBinding : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull secret;
- (nonnull instancetype)initWithSecret:(NSString * _Nonnull)secret OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FinvuLoginResponse")
@interface FinvuLoginResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSError;
@class FinvuLoginOtpReference;
@class FinvuHandleInfo;
@class FinvuLinkedAccountsReponse;
@class FinvuTypeIdentifierInfo;
@class FinvuLinkedAccountDetailsInfo;
@class FinvuProcessAccountConsentResponse;
@class FinvuUserConsentInfoDetails;

SWIFT_CLASS("_TtC8FinvuSDK12FinvuManager")
@interface FinvuManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) FinvuManager * _Nonnull shared;)
+ (FinvuManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(FinvuManager * _Nonnull)value;
- (void)setCompletionDispatchQueueWithQueue:(dispatch_queue_t _Nonnull)queue;
- (void)initializeWithConfig:(id <FinvuConfig> _Nonnull)config;
- (void)connectWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)disconnect;
- (BOOL)isConnected SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasSession SWIFT_WARN_UNUSED_RESULT;
- (void)loginWithUsername:(NSString * _Nullable)username mobileNumber:(NSString * _Nullable)mobileNumber consentHandleId:(NSString * _Nonnull)consentHandleId completion:(void (^ _Nonnull)(FinvuLoginOtpReference * _Nullable, NSError * _Nullable))completion;
- (void)verifyLoginOtpWithOtp:(NSString * _Nonnull)otp otpReference:(NSString * _Nonnull)otpReference completion:(void (^ _Nonnull)(FinvuHandleInfo * _Nullable, NSError * _Nullable))completion;
- (void)initiateMobileVerificationWithMobileNumber:(NSString * _Nonnull)mobileNumber completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)completeMobileVerificationWithMobileNumber:(NSString * _Nonnull)mobileNumber otp:(NSString * _Nonnull)otp completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)fetchLinkedAccountsWithCompletion:(void (^ _Nonnull)(FinvuLinkedAccountsReponse * _Nullable, NSError * _Nullable))completion;
- (void)discoverAccountsWithFipDetails:(FinvuFIPDetails * _Nonnull)fipDetails fiTypes:(NSArray<NSString *> * _Nonnull)fiTypes identifiers:(NSArray<FinvuTypeIdentifierInfo *> * _Nonnull)identifiers completion:(void (^ _Nonnull)(FinvuDiscoveredAccountsResponse * _Nullable, NSError * _Nullable))completion;
- (void)linkAccountsWithFipDetails:(FinvuFIPDetails * _Nonnull)fipDetails accounts:(NSArray<FinvuDiscoveredAccountInfo *> * _Nonnull)accounts completion:(void (^ _Nonnull)(FinvuAccountLinkingRequestReference * _Nullable, NSError * _Nullable))completion;
- (void)confirmAccountLinkingWithLinkingReference:(FinvuAccountLinkingRequestReference * _Nonnull)linkingReference otp:(NSString * _Nonnull)otp completion:(void (^ _Nonnull)(FinvuConfirmAccountLinkingInfo * _Nullable, NSError * _Nullable))completion;
- (void)getConsentRequestDetailsWithConsentHandleId:(NSString * _Nonnull)consentHandleId completion:(void (^ _Nonnull)(FinvuConsentRequestDetailResponse * _Nullable, NSError * _Nullable))completion;
- (void)approveAccountConsentRequestWithConsentDetail:(FinvuConsentRequestDetailInfo * _Nonnull)consentDetail linkedAccounts:(NSArray<FinvuLinkedAccountDetailsInfo *> * _Nonnull)linkedAccounts completion:(void (^ _Nonnull)(FinvuProcessAccountConsentResponse * _Nullable, NSError * _Nullable))completion;
- (void)denyAccountConsentRequestWithConsentDetail:(FinvuConsentRequestDetailInfo * _Nonnull)consentDetail completion:(void (^ _Nonnull)(FinvuProcessAccountConsentResponse * _Nullable, NSError * _Nullable))completion;
- (void)revokeConsentWithConsent:(FinvuUserConsentInfoDetails * _Nonnull)consent accountAggregator:(FinvuAccountAggregator * _Nullable)accountAggregator fipDetails:(FinvuFIPReference * _Nullable)fipDetails completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)getConsentHandleStatusWithHandleId:(NSString * _Nonnull)handleId completion:(void (^ _Nonnull)(FinvuConsentHandleStatusResponse * _Nullable, NSError * _Nullable))completion;
- (void)fipsAllFIPOptionsWithCompletion:(void (^ _Nonnull)(FinvuFIPSearchResponse * _Nullable, NSError * _Nullable))completion;
- (void)fetchFIPDetailsWithFipId:(NSString * _Nonnull)fipId completion:(void (^ _Nonnull)(FinvuFIPDetails * _Nullable, NSError * _Nullable))completion;
- (void)getEntityInfoWithEntityId:(NSString * _Nonnull)entityId entityType:(NSString * _Nonnull)entityType completion:(void (^ _Nonnull)(FinvuEntityInfo * _Nullable, NSError * _Nullable))completion;
- (void)logoutWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end


SWIFT_CLASS_NAMED("ForgotHandle")
@interface FinvuForgotHandle : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull userIds;
- (nonnull instancetype)initWithUserIds:(NSArray<NSString *> * _Nonnull)userIds OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("HandleInfo")
@interface FinvuHandleInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LinkedAccountDetailsInfo")
@interface FinvuLinkedAccountDetailsInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
@property (nonatomic, readonly, copy) NSString * _Nonnull fipId;
@property (nonatomic, readonly, copy) NSString * _Nonnull fipName;
@property (nonatomic, readonly, copy) NSString * _Nonnull maskedAccountNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull linkReferenceNumber;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable consentIdList;
@property (nonatomic, readonly, copy) NSString * _Nonnull fiType;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountType;
@property (nonatomic, readonly, copy) NSDate * _Nullable linkedAccountUpdateTimestamp;
@property (nonatomic, readonly, copy) NSString * _Nonnull authenticatorType;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId fipId:(NSString * _Nonnull)fipId fipName:(NSString * _Nonnull)fipName maskedAccountNumber:(NSString * _Nonnull)maskedAccountNumber accountReferenceNumber:(NSString * _Nonnull)accountReferenceNumber linkReferenceNumber:(NSString * _Nonnull)linkReferenceNumber consentIdList:(NSArray<NSString *> * _Nullable)consentIdList fiType:(NSString * _Nonnull)fiType accountType:(NSString * _Nonnull)accountType linkedAccountUpdateTimestamp:(NSDate * _Nullable)linkedAccountUpdateTimestamp authenticatorType:(NSString * _Nonnull)authenticatorType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LinkedAccountInfo")
@interface FinvuLinkedAccountInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull customerAddress;
@property (nonatomic, readonly, copy) NSString * _Nonnull linkReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountReferenceNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (nonnull instancetype)initWithCustomerAddress:(NSString * _Nonnull)customerAddress linkReferenceNumber:(NSString * _Nonnull)linkReferenceNumber accountReferenceNumber:(NSString * _Nonnull)accountReferenceNumber status:(NSString * _Nonnull)status OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LinkedAccountsResponse")
@interface FinvuLinkedAccountsReponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuLinkedAccountDetailsInfo *> * _Nullable linkedAccounts;
- (nonnull instancetype)initWithLinkedAccounts:(NSArray<FinvuLinkedAccountDetailsInfo *> * _Nullable)linkedAccounts OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LoginOtpReference")
@interface FinvuLoginOtpReference : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull reference;
- (nonnull instancetype)initWithReference:(NSString * _Nonnull)reference OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS_NAMED("OfflineMessageInfo")
@interface FinvuOfflineMessageInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageId;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageAcked;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageOriginator;
@property (nonatomic, readonly, copy) NSString * _Nullable messageOriginatorName;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageText;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageTimestamp;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageType;
@property (nonatomic, readonly, copy) NSString * _Nonnull requestConsentId;
@property (nonatomic, readonly, copy) NSString * _Nullable requestSessionId;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId messageId:(NSString * _Nonnull)messageId messageAcked:(NSString * _Nonnull)messageAcked messageOriginator:(NSString * _Nonnull)messageOriginator messageOriginatorName:(NSString * _Nullable)messageOriginatorName messageText:(NSString * _Nonnull)messageText messageTimestamp:(NSString * _Nonnull)messageTimestamp messageType:(NSString * _Nonnull)messageType requestConsentId:(NSString * _Nonnull)requestConsentId requestSessionId:(NSString * _Nullable)requestSessionId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PendingConsentRequestsResponse")
@interface FinvuPendingConsentRequestsResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuConsentRequestDetailInfo *> * _Nonnull details;
- (nonnull instancetype)initWithDetails:(NSArray<FinvuConsentRequestDetailInfo *> * _Nonnull)details OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ProcessAccountConsentResponse")
@interface FinvuProcessAccountConsentResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable consentIntentId;
@property (nonatomic, readonly, copy) NSArray<FinvuConsentInfo *> * _Nullable consentsInfo;
- (nonnull instancetype)initWithConsentIntentId:(NSString * _Nullable)consentIntentId consentsInfo:(NSArray<FinvuConsentInfo *> * _Nullable)consentsInfo OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("TypeIdentifier")
@interface FinvuTypeIdentifier : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category type:(NSString * _Nonnull)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("TypeIdentifierInfo")
@interface FinvuTypeIdentifierInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull value;
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category type:(NSString * _Nonnull)type value:(NSString * _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UserConsentDetails")
@interface FinvuUserConsentDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable consentHandle;
@property (nonatomic, readonly, copy) NSString * _Nullable consentId;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentStatus;
@property (nonatomic, readonly, copy) NSDate * _Nullable statusLastUpdateTimestamp;
@property (nonatomic, readonly, strong) FinvuFinancialInformationUserInfo * _Nullable financialInformationProvider;
@property (nonatomic, readonly, strong) FinvuFinancialInformationUserInfo * _Nullable financialInformationUser;
@property (nonatomic, readonly, strong) FinvuConsentPurposeInfo * _Nonnull consentPurposeInfo;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull consentDisplayDescriptions;
@property (nonatomic, readonly, strong) FinvuDateTimeRange * _Nonnull consentDateTimeRange;
@property (nonatomic, readonly, strong) FinvuDateTimeRange * _Nonnull dataDateTimeRange;
@property (nonatomic, readonly, strong) FinvuConsentDataLifePeriod * _Nonnull consentDataLifePeriod;
@property (nonatomic, readonly, strong) FinvuConsentDataFrequency * _Nonnull consentDataFrequency;
@property (nonatomic, readonly, copy) NSArray<FinvuConsentAccountDetails *> * _Nonnull accounts;
@property (nonatomic, readonly, strong) FinvuAccountAggregator * _Nonnull accountAggregator;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UserConsentInfo")
@interface FinvuUserConsentInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull consentIntentId;
@property (nonatomic, readonly, copy) NSString * _Nullable consentIntentEntityId;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentIntentEntityName;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull consentIdList;
@property (nonatomic, readonly, copy) NSDate * _Nonnull consentIntentUpdateTimestamp;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentPurposeText;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
- (nonnull instancetype)initWithConsentIntentId:(NSString * _Nonnull)consentIntentId consentIntentEntityId:(NSString * _Nullable)consentIntentEntityId consentIntentEntityName:(NSString * _Nonnull)consentIntentEntityName consentIdList:(NSArray<NSString *> * _Nonnull)consentIdList consentIntentUpdateTimestamp:(NSDate * _Nonnull)consentIntentUpdateTimestamp consentPurposeText:(NSString * _Nonnull)consentPurposeText status:(NSString * _Nullable)status OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UserConsentInfoDetails")
@interface FinvuUserConsentInfoDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull consentId;
@property (nonatomic, readonly, copy) NSString * _Nullable consentIntentEntityId;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentIntentEntityName;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull consentIdList;
@property (nonatomic, readonly, copy) NSDate * _Nonnull consentIntentUpdateTimestamp;
@property (nonatomic, readonly, copy) NSString * _Nonnull consentPurposeText;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
- (nonnull instancetype)initWithConsentId:(NSString * _Nonnull)consentId consentIntentEntityId:(NSString * _Nullable)consentIntentEntityId consentIntentEntityName:(NSString * _Nonnull)consentIntentEntityName consentIdList:(NSArray<NSString *> * _Nonnull)consentIdList consentIntentUpdateTimestamp:(NSDate * _Nonnull)consentIntentUpdateTimestamp consentPurposeText:(NSString * _Nonnull)consentPurposeText status:(NSString * _Nullable)status OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UserConsentResponse")
@interface FinvuUserConsentResponse : NSObject
@property (nonatomic, readonly, copy) NSArray<FinvuUserConsentInfo *> * _Nonnull userConsents;
- (nonnull instancetype)initWithUserConsents:(NSArray<FinvuUserConsentInfo *> * _Nonnull)userConsents OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UserInfo")
@interface FinvuUserInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
@property (nonatomic, readonly, copy) NSString * _Nonnull mobileNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull emailId;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId mobileNumber:(NSString * _Nonnull)mobileNumber emailId:(NSString * _Nonnull)emailId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
